spring:
  profiles:
    default: prod
  application:
    name: ready-auction
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: none
logging:
  level:
    root: info
    com.readyauction.app: debug

server:
  servlet:
    context-path: /app