spring:
  profiles:
    default: test
  application:
    name: ready-auction
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # 이 부분을 추가합니다.
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update # 또는 create, create-drop, validate 중 선택
logging:
  level:
    root: info
    com.readyauction.app: debug

server:
  servlet:
    context-path: /app