# 사용자 정의 속성
profile:
  value: 'prod'
spring:
  datasource:
    url: jdbc:mysql://wittdbreal.chr10oalkvb3.ap-northeast-2.rds.amazonaws.com:3306/auctiondb
    username: admin
    password: RKAWK78044***
    driver-class-name: com.mysql.cj.jdbc.Driver

