# 사용자 정의 속성
profile:
  value: 'prod'
spring:
  datasource:
    url: jdbc:mysql://223.130.154.162/auctiondb
    username: readyauction
    password: Ready?Auction!1
    driver-class-name: com.mysql.cj.jdbc.Driver

