spring:
  application:
    name: ready-auction
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: info
    com.readyauction.app: debug

server:
  servlet:
    context-path: /app