spring:
  application:
    name: ready-auction
  datasource:
    url: jdbc:mysql://192.168.219.106/readyauctiondb
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      max-lifetime: 60000
      minimum-idle: 5
      idle-timeout: 30000
      auto-commit: false
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    root: info
    com.readyauction.app: debug

server:
  servlet:
    context-path: /app

ftp:
  server:
    host: 192.168.219.106
    port: 21
    username: root
    password: mysql