spring:
  profiles:
    default: test
  application:
    name: ready-auction
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update # 이 부분을 추가합니다.
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl:
          auto: update # 또는 create, create-drop, validate 중 선택
  s3:
    accessKey: ${SPRING_S3_ACCESSKEY}
    secretKey: ${SPRING_S3_SECRETKEY}
    bucket: ready-auction-bucket

logging:
  level:
    root: info
    com.readyauction.app: debug

server:
  servlet:
    context-path: /app

file:
  upload-dir: /path/to/upload/directory

  spring:
    redis:
      host: localhost
      port: 6379

  redis:
    bid:
      prefix: bids